project:
  type: website
  output-dir: docs

filters:
  - timer

website:
  title: "Praktikum"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right: 
      - href: /de
        text: Deutsch
    #  - icon: github
     #   href: https://github.com/IgnaLeiva/plottingR
    #  - text: <img src="/qr.png" height="50px" style="vertical-align: middle;">
     #   href: qr.png
  #page-footer: 
 #   left: "Copyright 2021, Norah Jones" 
  #  right: 
   #   - icon: github
   #     href: https://github.com/

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    title: "dhdhThis is d"
    logo: mfm-logo.svg
    pinned: true
    style: docked        # or "floating"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: praktikum1/praktikum1.qmd
        text: "Practical 1: SPSS installation"
      - href: praktikum2/praktikum2.qmd
        text: Practical 2
      - href: praktikum3/praktikum3.qmd
        text: Practical 3
      - href: pvalue.qmd
        text: "p-value"
 #     - href: 
 #       text: Practical 4
      - href: praktikum5/praktikum5.qmd
        text: Practical 5
#      - href: 
#        text: Practical 6
 #     - href: 
 #       text: Practical 7
      - href: blackboard.qmd
        text: "Blackboard"
        target: _blank 
lang: en

format:
  html:
    df-print: paged
    grid:
      sidebar-width: 300px
      body-width: 2000px
      margin-width: 300px
      gutter-width: 1.5rem
    theme: 
       - cosmo
       - style.scss
   # css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    include-after-body: utilities/language_switcher.html

date: last-modified

metadata:
  lang: "en"